import axios from "axios";
import Head from "next/head";
import { useEffect,useState } from "react";

const fetch = async (locale) => {
  const response = await axios.get(
    `http://localhost:3000/api/users?locale=${locale}`
  );
  return response.data.data;
};

// export const getStaticProps = async () => {
//   const response = await axios.get(`http://localhost:3000/api/users`)

//   if (!response.data) {
//     return {
//       notFound: true,
//     }
//   }

//   return {
//     props: { posts: response.data },
//   }
// };

export default function Home({ posts }) {
  const [localTranslate, setLocalTranslate] = useState(null);
  const [locale, setLocale] = useState("en");

  useEffect(() => {
    fetch(locale).then((data) => {
      setLocalTranslate(data);
    });
  }, [locale]);

  console.log(localTranslate);
  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>
        <select
          defaultValue={locale}
          onChange={(e) => setLocale(e.target.value)}
        >
          <option value="ua">UA</option>
          <option value="de">DE</option>
          <option value="en">EN</option>
        </select>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800">
              Add Employee <span className="px-1"></span>
            </button>
          </div>
        </div>

        <div className="container mx-auto">
          <ul>
            {localTranslate &&
              Object.keys(localTranslate).map((constant) => {
                return (
                  <li key={constant}>
                    {constant}: {localTranslate[constant]}
                  </li>
                );
              })}
          </ul>
        </div>
      </main>
    </section>
  );
}
